apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: travelly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: i222467/travelly-admin:latest
        ports:
        - containerPort: 3003
        env:
        - name: NODE_ENV
          value: "production"
        - name: REACT_APP_API_URL
          value: "http://backend-service.travelly.svc.cluster.local:3000"
        - name: JWT_SECRET
          value: "L^E&404a5r-s9^:"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3003
          initialDelaySeconds: 5
          periodSeconds: 5 