apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: travelly
spec:
  type: NodePort
  selector:
    app: admin
  ports:
    - port: 80
      targetPort: 3003
      nodePort: 30002
      protocol: TCP
      name: http 